"use strict";

// Константы для лимитов и ограничений
const LIMITS = {
  MAX_PAGE_SIZE: 50,
  MAX_SEARCH_LENGTH: 100,
  MAX_NAME_LENGTH: 100,
  MAX_DESCRIPTION_LENGTH: 500,
  MAX_MESSAGE_LENGTH: 4096,
  MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
  MAX_UPLOAD_FILES: 5,
  MAX_TEAM_MEMBERS: 50,
  MAX_WORK_HOURS_PER_DAY: 24,
  MAX_WORK_DAYS_PER_WEEK: 7,
  MAX_VACATION_DAYS: 365,
  MAX_SICK_DAYS: 365,
  MAX_OVERTIME_HOURS: 12,
  MAX_BREAK_MINUTES: 120,
  MAX_LATE_MINUTES: 60,
  MAX_EARLY_LEAVE_MINUTES: 60,
  MAX_ABSENCE_DAYS: 365,
  MAX_NOTIFICATION_LENGTH: 1000,
  MAX_LOG_ENTRIES: 1000,
  MAX_AUDIT_ENTRIES: 10000,
  MAX_METRICS_DAYS: 365,
  MAX_REPORT_DAYS: 365,
  MAX_SCHEDULE_DAYS: 365,
  MAX_REMINDER_DAYS: 365,
  MAX_TELEGRAM_MESSAGE_LENGTH: 4096,
  MAX_TELEGRAM_CAPTION_LENGTH: 1024,
  MAX_TELEGRAM_BUTTONS: 8,
  MAX_TELEGRAM_INLINE_BUTTONS: 64,
  MAX_TELEGRAM_POLL_OPTIONS: 10,
  MAX_TELEGRAM_POLL_QUESTION_LENGTH: 300,
  MAX_TELEGRAM_POLL_OPTION_LENGTH: 100,
  MAX_TELEGRAM_DICE_EMOJI: 6,
  MAX_TELEGRAM_DART_EMOJI: 6,
  MAX_TELEGRAM_BOWLING_EMOJI: 6,
  MAX_TELEGRAM_BASKETBALL_EMOJI: 5,
  MAX_TELEGRAM_FOOTBALL_EMOJI: 5,
  MAX_TELEGRAM_SLOT_MACHINE_EMOJI: 5,
  DEFAULT_PAGE_SIZE: 20,
  MAX_USERNAME_LENGTH: 50,
  MAX_EMAIL_LENGTH: 100,
  MAX_ROLE_LENGTH: 20,
  MAX_STATUS_LENGTH: 20
};

// HTTP статус коды
const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504
};

// Временные константы
const TIME_CONSTANTS = {
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  DAYS_PER_WEEK: 7,
  DAYS_PER_MONTH: 30,
  DAYS_PER_YEAR: 365,
  MILLISECONDS_PER_SECOND: 1000,
  MILLISECONDS_PER_MINUTE: TIME_CONSTANTS.SECONDS_PER_MINUTE * TIME_CONSTANTS.MILLISECONDS_PER_SECOND,
  MILLISECONDS_PER_HOUR: TIME_CONSTANTS.MINUTES_PER_HOUR * TIME_CONSTANTS.MILLISECONDS_PER_MINUTE,
  MILLISECONDS_PER_DAY: TIME_CONSTANTS.HOURS_PER_DAY * TIME_CONSTANTS.MILLISECONDS_PER_HOUR,
  MILLISECONDS_PER_WEEK: TIME_CONSTANTS.DAYS_PER_WEEK * TIME_CONSTANTS.MILLISECONDS_PER_DAY,
  MILLISECONDS_PER_MONTH: TIME_CONSTANTS.DAYS_PER_MONTH * TIME_CONSTANTS.MILLISECONDS_PER_DAY,
  MILLISECONDS_PER_YEAR: TIME_CONSTANTS.DAYS_PER_YEAR * TIME_CONSTANTS.MILLISECONDS_PER_DAY,
  MINUTE: TIME_CONSTANTS.MILLISECONDS_PER_MINUTE,
  HOUR: TIME_CONSTANTS.MILLISECONDS_PER_HOUR,
  DAY: TIME_CONSTANTS.MILLISECONDS_PER_DAY
};

module.exports = {
  LIMITS,
  HTTP_STATUS_CODES,
  TIME_CONSTANTS
}; 